/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
     @Override
    public int getWidth(ImageObserver observer) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public int getHeight(ImageObserver observer) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public ImageProducer getSource() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public Graphics getGraphics() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public Object getProperty(String name, ImageObserver observer) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
* Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tela;

import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author artur
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();

        this.setExtendedState(MAXIMIZED_BOTH);
        //this.setResizable(false);

        try {
            Image bgImg = ImageIO.read(new File("./src/img/background-image.jpg"));

        } catch (Exception e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        ImageIcon icon = new ImageIcon(getClass().getResource("/img/bg-img.jpg"));
        Image image = icon.getImage();
        DtpPrincipal = new javax.swing.JDesktopPane() {

            public void paintComponent(Graphics g) {
                g.drawImage(image, 0, 0, 2000, 1369, this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MitObjCadastrar = new javax.swing.JMenuItem();
        MitObjConsultar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MitPessoaCadastrar = new javax.swing.JMenuItem();
        MitPessoaConsultar = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MitEmpCadastrar = new javax.swing.JMenuItem();
        MitEmpConsultar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de Objetos");
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1280, 720));

        javax.swing.GroupLayout DtpPrincipalLayout = new javax.swing.GroupLayout(DtpPrincipal);
        DtpPrincipal.setLayout(DtpPrincipalLayout);
        DtpPrincipalLayout.setHorizontalGroup(
            DtpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 888, Short.MAX_VALUE)
        );
        DtpPrincipalLayout.setVerticalGroup(
            DtpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );

        jMenu1.setText("Objeto");

        MitObjCadastrar.setText("Cadastrar");
        MitObjCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MitObjCadastrarActionPerformed(evt);
            }
        });
        jMenu1.add(MitObjCadastrar);

        MitObjConsultar.setText("Consultar");
        MitObjConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MitObjConsultarActionPerformed(evt);
            }
        });
        jMenu1.add(MitObjConsultar);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Pessoa");

        MitPessoaCadastrar.setText("Cadastrar");
        MitPessoaCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MitPessoaCadastrarActionPerformed(evt);
            }
        });
        jMenu3.add(MitPessoaCadastrar);

        MitPessoaConsultar.setText("Consultar");
        MitPessoaConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MitPessoaConsultarActionPerformed(evt);
            }
        });
        jMenu3.add(MitPessoaConsultar);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Empréstimo");

        MitEmpCadastrar.setText("Cadastrar");
        MitEmpCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MitEmpCadastrarActionPerformed(evt);
            }
        });
        jMenu4.add(MitEmpCadastrar);

        MitEmpConsultar.setText("Consultar");
        jMenu4.add(MitEmpConsultar);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Ajuda");

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DtpPrincipal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DtpPrincipal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MitObjCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MitObjCadastrarActionPerformed
        IfrObjeto frmObjeto = new IfrObjeto();

        DtpPrincipal.add(frmObjeto);

        frmObjeto.focoCadastro();
        frmObjeto.setVisible(true);
    }//GEN-LAST:event_MitObjCadastrarActionPerformed

    private void MitObjConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MitObjConsultarActionPerformed
        IfrObjeto frmObjeto = new IfrObjeto();

        DtpPrincipal.add(frmObjeto);

        frmObjeto.focoListagem();
        frmObjeto.setVisible(true);
    }//GEN-LAST:event_MitObjConsultarActionPerformed

    private void MitPessoaCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MitPessoaCadastrarActionPerformed
        IfrPessoa framePessoa = new IfrPessoa();

        DtpPrincipal.add(framePessoa);

        framePessoa.focoCadastro();
        framePessoa.setVisible(true);
    }//GEN-LAST:event_MitPessoaCadastrarActionPerformed

    private void MitPessoaConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MitPessoaConsultarActionPerformed
        IfrPessoa framePessoa = new IfrPessoa();

        DtpPrincipal.add(framePessoa);

        framePessoa.focoListagem();
        framePessoa.setVisible(true);
    }//GEN-LAST:event_MitPessoaConsultarActionPerformed

    private void MitEmpCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MitEmpCadastrarActionPerformed
        IfrEmprestimo frameEmprestimo = new IfrEmprestimo();

        DtpPrincipal.add(frameEmprestimo);

        frameEmprestimo.setVisible(true);
    }//GEN-LAST:event_MitEmpCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DtpPrincipal;
    private javax.swing.JMenuItem MitEmpCadastrar;
    private javax.swing.JMenuItem MitEmpConsultar;
    private javax.swing.JMenuItem MitObjCadastrar;
    private javax.swing.JMenuItem MitObjConsultar;
    private javax.swing.JMenuItem MitPessoaCadastrar;
    private javax.swing.JMenuItem MitPessoaConsultar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
