/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package tela;

import DAO.ObjetoDAO;
import DAO.PessoaDAO;
import DAO.TipoObjetoDAO;
import entidade.Objeto;
import entidade.Pessoa;
import entidade.TipoObjeto;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author artur
 */
public class IfrEmprestimo extends javax.swing.JInternalFrame {

    ArrayList<Objeto> objetos = new ArrayList<>();
    ArrayList<Pessoa> pessoas = new ArrayList<>();
    ArrayList<TipoObjeto> tiposObjeto = new ArrayList<>();

    Objeto objetoSelecionado = null;
    Pessoa pessoaSelecionada = null;

    /**
     * Creates new form IfrEmprestimo
     */
    public IfrEmprestimo() {
        initComponents();

        popularTabelaObjetos();
        popularTabelaPessoas();
        popularComboBoxTipoObjeto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TbpPrincipal = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        TbpCadastroEmprestimo = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblObjetos = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CbbTipoObjeto = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        TxtFiltroDescricao = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TxtFiltroAutor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TxtFiltroPublisher = new javax.swing.JTextField();
        BtnObjLimparFiltro = new javax.swing.JButton();
        BtnObjFiltrar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblPessoas = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TxtFiltroNome = new javax.swing.JTextField();
        TxtFiltroApelido = new javax.swing.JTextField();
        BtnPessoaLimparFiltro = new javax.swing.JButton();
        BtnPessoaFiltrar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtDescricao = new javax.swing.JTextField();
        TxtAutor = new javax.swing.JTextField();
        TxtEditora = new javax.swing.JTextField();
        TxtTipoObjeto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        TxtNome = new javax.swing.JTextField();
        TxtApelido = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        BtnSelcionar = new javax.swing.JButton();
        BtnVoltar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        BtnBuscar = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();
        BtnCadastrar = new javax.swing.JButton();
        BtnFechar = new javax.swing.JButton();

        TbpPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );

        TbpPrincipal.addTab("Listagem", jPanel1);

        TbpCadastroEmprestimo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TblObjetos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Título/Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblObjetos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TblObjetos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblObjetosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblObjetos);
        if (TblObjetos.getColumnModel().getColumnCount() > 0) {
            TblObjetos.getColumnModel().getColumn(0).setResizable(false);
            TblObjetos.getColumnModel().getColumn(1).setResizable(false);
            TblObjetos.getColumnModel().getColumn(1).setPreferredWidth(350);
        }

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel6.setText("Filtros:");

        jLabel7.setText("Tipo:");

        jLabel9.setText("Título/Descrição:");

        jLabel10.setText("Autor:");

        jLabel11.setText("Editora/Produtora:");

        BtnObjLimparFiltro.setText("Limpar");
        BtnObjLimparFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnObjLimparFiltroActionPerformed(evt);
            }
        });

        BtnObjFiltrar.setText("Buscar");
        BtnObjFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnObjFiltrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtFiltroDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(TxtFiltroAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtFiltroPublisher)
                            .addComponent(CbbTipoObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(BtnObjLimparFiltro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnObjFiltrar)))
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CbbTipoObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TxtFiltroDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TxtFiltroAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(TxtFiltroPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnObjLimparFiltro)
                    .addComponent(BtnObjFiltrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TbpCadastroEmprestimo.addTab("Objeto", jPanel4);

        TblPessoas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Apelido", "Telefone", "e-mail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblPessoas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblPessoasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TblPessoas);

        jLabel12.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel12.setText("Filtros:");

        jLabel13.setText("Nome:");

        jLabel14.setText("Apelido:");

        BtnPessoaLimparFiltro.setText("Limpar");
        BtnPessoaLimparFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPessoaLimparFiltroActionPerformed(evt);
            }
        });

        BtnPessoaFiltrar.setText("Buscar");
        BtnPessoaFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPessoaFiltrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(TxtFiltroApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnPessoaLimparFiltro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnPessoaFiltrar))
                            .addComponent(TxtFiltroNome, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(TxtFiltroNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtFiltroApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnPessoaLimparFiltro)
                            .addComponent(BtnPessoaFiltrar)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)))
                .addContainerGap())
        );

        TbpCadastroEmprestimo.addTab("Pessoa", jPanel5);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel1.setText("Objeto selecionado");

        jLabel2.setText("Tipo:");

        jLabel3.setText("Título/Descrição:");

        jLabel5.setText("Autor:");

        jLabel4.setText("Editora/Produtora:");

        TxtDescricao.setEnabled(false);

        TxtAutor.setEnabled(false);

        TxtEditora.setEnabled(false);

        TxtTipoObjeto.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel8.setText("Emprestado para");

        jLabel15.setText("Nome:");

        jLabel16.setText("Apelido:");

        TxtNome.setEnabled(false);

        TxtApelido.setEnabled(false);

        jLabel17.setText("Data empréstimo:");

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel8)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtTipoObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(262, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtTipoObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TxtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(TxtApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        TbpCadastroEmprestimo.addTab("Empréstimo", jPanel6);

        TbpCadastroEmprestimo.setEnabledAt(0, false);
        TbpCadastroEmprestimo.setEnabledAt(1, false);
        TbpCadastroEmprestimo.setEnabledAt(2, false);

        BtnSelcionar.setText("Selecionar >");
        BtnSelcionar.setEnabled(false);
        BtnSelcionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSelcionarActionPerformed(evt);
            }
        });

        BtnVoltar.setText("< Voltar");
        BtnVoltar.setEnabled(false);
        BtnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TbpCadastroEmprestimo)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(BtnVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnSelcionar)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TbpCadastroEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSelcionar)
                    .addComponent(BtnVoltar))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        TbpPrincipal.addTab("Cadastro", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );

        TbpPrincipal.addTab("Edição/Atualização", jPanel3);

        BtnBuscar.setText("Buscar");

        BtnEditar.setText("Editar");

        BtnCadastrar.setText("Cadastrar");

        BtnFechar.setText("Fechar");
        BtnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TbpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(BtnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnFechar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TbpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnBuscar)
                    .addComponent(BtnEditar)
                    .addComponent(BtnCadastrar)
                    .addComponent(BtnFechar))
                .addContainerGap())
        );

        TbpPrincipal.setEnabledAt(2, false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSelcionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSelcionarActionPerformed
        int index = TbpCadastroEmprestimo.getSelectedIndex();

        switch (index) {
            case 0:
                objetoSelecionado = objetos.get(TblObjetos.getSelectedRow());
                TbpCadastroEmprestimo.setSelectedIndex(index + 1);
                imprimeObjetoSelecionado();
                break;
            case 1:
                pessoaSelecionada = pessoas.get(TblPessoas.getSelectedRow());
                TbpCadastroEmprestimo.setSelectedIndex(index + 1);
                imprimirPessoaSelecionada();
                break;
        }

        cadastroAlternarBotoes(index + 1);
    }//GEN-LAST:event_BtnSelcionarActionPerformed

    private void BtnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnFecharActionPerformed

    private void BtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltarActionPerformed
        int index = TbpCadastroEmprestimo.getSelectedIndex();

        if (index > 0) {
            TbpCadastroEmprestimo.setSelectedIndex(index - 1);
        }

        cadastroAlternarBotoes(index - 1);
        BtnSelcionar.setEnabled(false);
    }//GEN-LAST:event_BtnVoltarActionPerformed

    private void BtnObjFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnObjFiltrarActionPerformed
        popularTabelaObjetos();
        BtnSelcionar.setEnabled(false);
    }//GEN-LAST:event_BtnObjFiltrarActionPerformed

    private void TblObjetosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblObjetosMouseClicked
        if (TblObjetos.getSelectedRow() >= 0) {
            BtnSelcionar.setEnabled(true);
        }
    }//GEN-LAST:event_TblObjetosMouseClicked

    private void TblPessoasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblPessoasMouseClicked
        if (TblPessoas.getSelectedRow() >= 0) {
            BtnSelcionar.setEnabled(true);
        }
    }//GEN-LAST:event_TblPessoasMouseClicked

    private void BtnPessoaFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPessoaFiltrarActionPerformed
        popularTabelaPessoas();
        BtnSelcionar.setEnabled(false);
    }//GEN-LAST:event_BtnPessoaFiltrarActionPerformed

    private void BtnObjLimparFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnObjLimparFiltroActionPerformed
        limparFiltroObjeto();
        popularTabelaObjetos();
        BtnSelcionar.setEnabled(false);
    }//GEN-LAST:event_BtnObjLimparFiltroActionPerformed

    private void BtnPessoaLimparFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPessoaLimparFiltroActionPerformed
        limparFiltroPessoa();
        popularTabelaPessoas();
        BtnSelcionar.setEnabled(false);
    }//GEN-LAST:event_BtnPessoaLimparFiltroActionPerformed

    private void cadastroAlternarBotoes(int index) {
        BtnSelcionar.setEnabled(false);
        BtnVoltar.setEnabled(index != 0);
    }

    private void popularArrayObjetos() {
        ObjetoDAO objetoDAO = new ObjetoDAO();

        objetos = objetoDAO.consultar(criarFiltroObjeto());
    }

    private void popularTabelaObjetos() {
        popularArrayObjetos();

        limparTabelaObjetos();

        TipoObjetoDAO tipoObjetoDAO = new TipoObjetoDAO();

        DefaultTableModel model = (DefaultTableModel) TblObjetos.getModel();

        for (Objeto objeto : objetos) {
            TipoObjeto tipo = tipoObjetoDAO.consultarId(objeto.getTipo());

            String tipoDesc = tipo.getDescricao();
            String titulo = objeto.getTitulo();

            String[] row = {tipoDesc, titulo};

            model.addRow(row);
        }

        TblObjetos.setModel(model);
    }

    private void limparTabelaObjetos() {
        DefaultTableModel model = (DefaultTableModel) TblObjetos.getModel();
        model.setRowCount(0);
    }

    private void popularArrayPessoas() {
        PessoaDAO pessoaDAO = new PessoaDAO();

        pessoas = pessoaDAO.consultar(criarFiltroPessoa());
    }

    public void limparTabelaPessoas() {
        DefaultTableModel model = (DefaultTableModel) TblPessoas.getModel();

        model.setRowCount(0);

        TblPessoas.setModel(model);
    }

    public void popularTabelaPessoas() {
        popularArrayPessoas();

        limparTabelaPessoas();

        DefaultTableModel model = (DefaultTableModel) TblPessoas.getModel();

        for (Pessoa pessoa : pessoas) {
            String nome = pessoa.getNome();
            String apelido = pessoa.getApelido();
            String telefone = pessoa.getTelefone();
            String email = pessoa.getEmail();

            String[] row = {nome, apelido, telefone, email};

            model.addRow(row);
        }

        TblPessoas.setModel(model);
    }

    private String criarFiltroPessoa() {
        String dml = "SELECT * FROM pessoa WHERE id > 0 ";

        if (TxtFiltroNome.getText().length() != 0) {
            String add = "AND nome ILIKE '%" + TxtFiltroNome.getText() + "%' ";
            dml = dml + add;
        }

        if (TxtFiltroApelido.getText().length() != 0) {
            String add = "AND apelido ILIKE '%" + TxtFiltroApelido.getText() + "%' ";
            dml = dml + add;
        }

        dml = dml + "ORDER BY nome;";

        return dml;
    }

    private String criarFiltroObjeto() {
        String dml = "SELECT * FROM objeto WHERE status_id = 1 ";

        if (CbbTipoObjeto.getSelectedIndex() > 0) {
            String add = "AND tipo_objeto_id = " + tiposObjeto.get(CbbTipoObjeto.getSelectedIndex() - 1).getId() + " ";
            dml = dml + add;
        }

        if (TxtFiltroDescricao.getText().length() > 0) {
            String add = "AND titulo ILIKE '%" + TxtFiltroDescricao.getText() + "%' ";
            dml = dml + add;
        }

        if (TxtFiltroAutor.getText().length() > 0) {
            String add = "AND autor ILIKE '%" + TxtFiltroAutor.getText() + "%' ";
            dml = dml + add;
        }

        if (TxtFiltroPublisher.getText().length() > 0) {
            String add = "AND publisher ILIKE '%" + TxtFiltroPublisher.getText() + "%' ";
            dml = dml + add;
        }

        dml = dml + "ORDER BY titulo;";

        System.out.println("DML: " + dml);

        return dml;
    }

    private void popularComboBoxTipoObjeto() {
        TipoObjetoDAO tipoObjetoDAO = new TipoObjetoDAO();
        tiposObjeto = tipoObjetoDAO.consultarTodos();
        CbbTipoObjeto.removeAllItems();

        CbbTipoObjeto.addItem("-- Selecione --");

        for (TipoObjeto tipo : tiposObjeto) {
            CbbTipoObjeto.addItem(tipo.getDescricao());
        }
    }

    private void imprimeObjetoSelecionado() {
        TipoObjetoDAO tipoObjetoDAO = new TipoObjetoDAO();
        TipoObjeto tipo = tipoObjetoDAO.consultarId(objetoSelecionado.getTipo());

        String tipoDesc = tipo.getDescricao();

        TxtTipoObjeto.setText(tipoDesc);
        TxtDescricao.setText(objetoSelecionado.getTitulo());
        TxtAutor.setText(objetoSelecionado.getAutor());
        TxtEditora.setText(objetoSelecionado.getPublisher());
    }

    private void imprimirPessoaSelecionada() {
        TxtNome.setText(pessoaSelecionada.getNome());
        TxtApelido.setText(pessoaSelecionada.getApelido());
    }
    
    private void limparFiltroObjeto() {
        CbbTipoObjeto.setSelectedIndex(0);
        TxtFiltroDescricao.setText("");
        TxtFiltroAutor.setText("");
        TxtFiltroPublisher.setText("");
    }
    
    private void limparFiltroPessoa() {
        TxtFiltroNome.setText("");
        TxtFiltroApelido.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnCadastrar;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnFechar;
    private javax.swing.JButton BtnObjFiltrar;
    private javax.swing.JButton BtnObjLimparFiltro;
    private javax.swing.JButton BtnPessoaFiltrar;
    private javax.swing.JButton BtnPessoaLimparFiltro;
    private javax.swing.JButton BtnSelcionar;
    private javax.swing.JButton BtnVoltar;
    private javax.swing.JComboBox<String> CbbTipoObjeto;
    private javax.swing.JTable TblObjetos;
    private javax.swing.JTable TblPessoas;
    private javax.swing.JTabbedPane TbpCadastroEmprestimo;
    private javax.swing.JTabbedPane TbpPrincipal;
    private javax.swing.JTextField TxtApelido;
    private javax.swing.JTextField TxtAutor;
    private javax.swing.JTextField TxtDescricao;
    private javax.swing.JTextField TxtEditora;
    private javax.swing.JTextField TxtFiltroApelido;
    private javax.swing.JTextField TxtFiltroAutor;
    private javax.swing.JTextField TxtFiltroDescricao;
    private javax.swing.JTextField TxtFiltroNome;
    private javax.swing.JTextField TxtFiltroPublisher;
    private javax.swing.JTextField TxtNome;
    private javax.swing.JTextField TxtTipoObjeto;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
