/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package tela;

import DAO.ObjetoDAO;
import DAO.StatusDAO;
import DAO.TipoObjetoDAO;
import apoio.Automatizar;
import apoio.ComboItem;
import apoio.CombosDAO;
import apoio.Formatacao;
import entidade.Objeto;
import entidade.Status;
import entidade.TipoObjeto;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author artur
 */
public class IfrObjeto extends javax.swing.JInternalFrame {

    private ArrayList<TipoObjeto> tiposObjeto = new ArrayList<>();
    private ArrayList<Objeto> objetos = new ArrayList<>();
    private Objeto objetoSelecionado = null;

    /**
     * Creates new form IfrObjeto
     */
    public IfrObjeto() {
        initComponents();

        new CombosDAO().popularComboBox("tipo_objeto", cmbFiltroTipo);
        new CombosDAO().popularComboBox("status", cmbFiltroStatus, "WHERE tipo = 0 ");
        new CombosDAO().popularComboBox("tipo_objeto", cmbTipoObjeto);

        popularTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TbpObjeto = new javax.swing.JTabbedPane();
        PnlListagem = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListagem = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbFiltroTipo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cmbFiltroStatus = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        tfdFiltroDescricao = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfdFiltroAutor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfdFiltroEditora = new javax.swing.JTextField();
        btnLimparFiltros = new javax.swing.JButton();
        PnlCadastrar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbTipoObjeto = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        tfdDescricao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfdAutor = new javax.swing.JTextField();
        tfdEditora = new javax.swing.JTextField();
        btnNovoTipoObjeto = new javax.swing.JButton();
        btnEditarTipoObjeto = new javax.swing.JButton();
        btnExcluirTipoObjeto = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnPerdido = new javax.swing.JButton();

        setTitle("Objeto");

        TbpObjeto.setToolTipText("");
        TbpObjeto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbpObjetoMouseClicked(evt);
            }
        });

        tblListagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListagemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblListagem);

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel6.setText("Filtros:");

        jLabel7.setText("Tipo:");

        jLabel8.setText("Status:");

        jLabel9.setText("Título/Descrição:");

        jLabel10.setText("Autor:");

        jLabel11.setText("Editora/Produtora:");

        btnLimparFiltros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/broom.png"))); // NOI18N
        btnLimparFiltros.setText("Limpar");
        btnLimparFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparFiltrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlListagemLayout = new javax.swing.GroupLayout(PnlListagem);
        PnlListagem.setLayout(PnlListagemLayout);
        PnlListagemLayout.setHorizontalGroup(
            PnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlListagemLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(PnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(PnlListagemLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(PnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlListagemLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbFiltroTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbFiltroStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlListagemLayout.createSequentialGroup()
                                .addGroup(PnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfdFiltroDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(tfdFiltroAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfdFiltroEditora))
                                .addGap(18, 18, 18)
                                .addComponent(btnLimparFiltros)))))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(PnlListagemLayout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        PnlListagemLayout.setVerticalGroup(
            PnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlListagemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbFiltroTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cmbFiltroStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfdFiltroDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfdFiltroAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfdFiltroEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimparFiltros))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        TbpObjeto.addTab("Listagem", PnlListagem);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel1.setText("Novo Objeto");

        jLabel2.setText("Tipo:");

        cmbTipoObjeto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTipoObjetoItemStateChanged(evt);
            }
        });
        cmbTipoObjeto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbTipoObjetoFocusLost(evt);
            }
        });

        jLabel3.setText("Título/Descrição:");

        tfdDescricao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdDescricaoFocusLost(evt);
            }
        });

        jLabel5.setText("Autor:");

        jLabel4.setText("Editora/Produtora:");

        tfdAutor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdAutorFocusLost(evt);
            }
        });

        tfdEditora.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdEditoraFocusLost(evt);
            }
        });

        btnNovoTipoObjeto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add-file.png"))); // NOI18N
        btnNovoTipoObjeto.setToolTipText("Novo Tipo de Objeto");
        btnNovoTipoObjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoTipoObjetoActionPerformed(evt);
            }
        });

        btnEditarTipoObjeto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pencil.png"))); // NOI18N
        btnEditarTipoObjeto.setToolTipText("Editar Tipo de Objeto");
        btnEditarTipoObjeto.setEnabled(false);
        btnEditarTipoObjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarTipoObjetoActionPerformed(evt);
            }
        });

        btnExcluirTipoObjeto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trash-bin.png"))); // NOI18N
        btnExcluirTipoObjeto.setToolTipText("Excuir Tipo de Objeto");
        btnExcluirTipoObjeto.setEnabled(false);
        btnExcluirTipoObjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirTipoObjetoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlCadastrarLayout = new javax.swing.GroupLayout(PnlCadastrar);
        PnlCadastrar.setLayout(PnlCadastrarLayout);
        PnlCadastrarLayout.setHorizontalGroup(
            PnlCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlCadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(PnlCadastrarLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(PnlCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnlCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfdDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PnlCadastrarLayout.createSequentialGroup()
                                .addComponent(cmbTipoObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnNovoTipoObjeto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditarTipoObjeto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExcluirTipoObjeto))
                            .addComponent(tfdAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfdEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        PnlCadastrarLayout.setVerticalGroup(
            PnlCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlCadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbTipoObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovoTipoObjeto)
                    .addComponent(btnEditarTipoObjeto)
                    .addComponent(btnExcluirTipoObjeto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfdDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfdAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfdEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(175, Short.MAX_VALUE))
        );

        TbpObjeto.addTab("Cadastrar", PnlCadastrar);

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add-file.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cross.png"))); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/loupe.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pencil.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trash-bin.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jSeparator1.setToolTipText("");

        btnPerdido.setIcon(new javax.swing.ImageIcon("D:\\PARTICULAR\\FACULDADE\\2023\\2023A2\\PROJETO INTEGRADOR - DESENVOLVIMENTO DE APLICAÇÕES - REF 348259\\Icones\\help.png")); // NOI18N
        btnPerdido.setText("Perdido");
        btnPerdido.setEnabled(false);
        btnPerdido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerdidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TbpObjeto)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btnPerdido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFechar))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TbpObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnFechar)
                    .addComponent(btnBuscar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir)
                    .addComponent(btnPerdido))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        objetoSelecionado = new ObjetoDAO().consultarId(objetos.get(tblListagem.getSelectedRow()).getId());
        preencherFormularioEdicao();
        TbpObjeto.setSelectedIndex(1);
        alterarBotoesEdicao(false);
        alternarBotoes();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void TbpObjetoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbpObjetoMouseClicked
        alternarBotoes();

        if (TbpObjeto.getSelectedIndex() == 1) {
            alterarBotoesEdicao(false);
        } else {
            limparFormularioCadastro();
            objetoSelecionado = null;
        }
    }//GEN-LAST:event_TbpObjetoMouseClicked

    private void btnNovoTipoObjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoTipoObjetoActionPerformed
        new DlgTipoObjeto(null, true, 0, cmbTipoObjeto).setVisible(true);
        btnEditarTipoObjeto.setEnabled(false);
    }//GEN-LAST:event_btnNovoTipoObjetoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        String msg = Formatacao.mensagemConfirmacaoAtualizar("Objeto");
        if (objetoSelecionado == null) {
            msg = Formatacao.mensagemConfirmacaoSalvar("Objeto");
        }

        if (verificarCampos()) {
            JOptionPane.showMessageDialog(this, Formatacao.mensagemErroPreenchimento());
        } else {
            if (JOptionPane.showConfirmDialog(this, msg, "Confirmação", JOptionPane.YES_NO_OPTION) == 0) {
                salvar();
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void tfdDescricaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdDescricaoFocusLost
        Automatizar.nome(tfdDescricao, false);
    }//GEN-LAST:event_tfdDescricaoFocusLost

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        popularTabela();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tfdEditoraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdEditoraFocusLost
        Automatizar.nome(tfdEditora, false);
    }//GEN-LAST:event_tfdEditoraFocusLost

    private void tfdAutorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdAutorFocusLost
        Automatizar.nome(tfdAutor, true);
    }//GEN-LAST:event_tfdAutorFocusLost

    private void cmbTipoObjetoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbTipoObjetoFocusLost
        Automatizar.comboBox(cmbTipoObjeto, false);
    }//GEN-LAST:event_cmbTipoObjetoFocusLost

    private void btnEditarTipoObjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarTipoObjetoActionPerformed
        ComboItem itemSelecionado = (ComboItem) cmbTipoObjeto.getSelectedItem();
        new DlgTipoObjeto(null, true, itemSelecionado.getId(), cmbTipoObjeto).setVisible(true);
        btnEditarTipoObjeto.setEnabled(false);
    }//GEN-LAST:event_btnEditarTipoObjetoActionPerformed

    private void cmbTipoObjetoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTipoObjetoItemStateChanged
        if (cmbTipoObjeto.getSelectedIndex() > 0) {
            btnEditarTipoObjeto.setEnabled(true);
            btnExcluirTipoObjeto.setEnabled(true);
        } else {
            btnEditarTipoObjeto.setEnabled(false);
            btnExcluirTipoObjeto.setEnabled(false);
        }
    }//GEN-LAST:event_cmbTipoObjetoItemStateChanged

    private void tblListagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListagemMouseClicked
        if (tblListagem.getSelectedRow() > -1) {
            alterarBotoesEdicao(true);
        }
    }//GEN-LAST:event_tblListagemMouseClicked

    private void btnExcluirTipoObjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirTipoObjetoActionPerformed
        ComboItem item = (ComboItem) cmbTipoObjeto.getSelectedItem();
        if (new TipoObjetoDAO().excluir(item.getId()) == null) {
            JOptionPane.showMessageDialog(this, "Tipo de Objeto excluído com sucesso!");
            new CombosDAO().popularComboBox("tipo_objeto", cmbTipoObjeto);
        } else {
            JOptionPane.showMessageDialog(this, "Não foi possível excluir este Tipo de Objeto.");
        }
    }//GEN-LAST:event_btnExcluirTipoObjetoActionPerformed

    private void btnLimparFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparFiltrosActionPerformed
        limparFiltros();
        popularTabela();
    }//GEN-LAST:event_btnLimparFiltrosActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        Objeto objeto = objetos.get(tblListagem.getSelectedRow());

        if (JOptionPane.showConfirmDialog(this, Formatacao.mensagemConfirmacaoExclusao("Objeto"), "Confirmação", JOptionPane.YES_NO_OPTION) == 0) {
            if (new ObjetoDAO().excluir(objeto.getId()) == null) {
                JOptionPane.showMessageDialog(this, Formatacao.mensagemExclusaoSucess("Objeto"));
            } else {
                JOptionPane.showMessageDialog(this, Formatacao.mensagemExclusaoError("Objeto"));
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnPerdidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerdidoActionPerformed
        Objeto objeto = objetos.get(tblListagem.getSelectedRow());

        if (JOptionPane.showConfirmDialog(this, Formatacao.mensagemConfirmacaoAtualizar("Objeto"), "Confirmação", JOptionPane.YES_NO_OPTION) == 0) {
            if (objeto.getStatus() == 3) {
                if (new ObjetoDAO().desfazerPerdido(objeto.getId()) == null) {
                    JOptionPane.showMessageDialog(this, Formatacao.mensagemAtualizarSucess("Objeto"));
                    popularTabela();
                } else {
                    JOptionPane.showMessageDialog(this, Formatacao.mensagemAtualizarError("Objeto"));
                }
            } else {
                if (new ObjetoDAO().estaPerdido(objeto.getId()) == null) {
                    JOptionPane.showMessageDialog(this, Formatacao.mensagemAtualizarSucess("Objeto"));
                    popularTabela();
                } else {
                    JOptionPane.showMessageDialog(this, Formatacao.mensagemAtualizarError("Objeto"));
                }
            }
        }
    }//GEN-LAST:event_btnPerdidoActionPerformed

    public void focoCadastro() {
        TbpObjeto.setSelectedIndex(1);
        alternarBotoes();
    }

    public void focoListagem() {
        TbpObjeto.setSelectedIndex(0);
        alternarBotoes();
    }

    private void alternarBotoes() {
        btnBuscar.setEnabled(TbpObjeto.getSelectedIndex() == 0);
        btnSalvar.setEnabled(TbpObjeto.getSelectedIndex() == 1);
    }

    private Objeto criarEntidade() {
        String titulo = tfdDescricao.getText();
        String autor = tfdAutor.getText();
        String publisher = tfdEditora.getText();
        int tipo = ((ComboItem) cmbTipoObjeto.getSelectedItem()).getId();
        int status = 1;

        if (objetoSelecionado == null) {
            return new Objeto(titulo, autor, publisher, status, tipo);
        } else {
            return new Objeto(objetoSelecionado.getId(), titulo, autor, publisher, objetoSelecionado.getStatus(), tipo);
        }
    }

    private void limparFormularioCadastro() {
        tfdDescricao.setText("");
        tfdAutor.setText("");
        tfdEditora.setText("");
        cmbTipoObjeto.setSelectedIndex(0);

        tfdDescricao.setBackground(Formatacao.colorNeutral());
        tfdAutor.setBackground(Formatacao.colorNeutral());
        tfdEditora.setBackground(Formatacao.colorNeutral());
        cmbTipoObjeto.setBorder(BorderFactory.createLineBorder(Formatacao.colorNeutral(), 0));

        tfdDescricao.requestFocus();
    }

    private void preencherFormularioEdicao() {
        tfdDescricao.setText(objetoSelecionado.getTitulo());
        tfdAutor.setText(objetoSelecionado.getAutor());
        tfdEditora.setText(objetoSelecionado.getPublisher());
        new CombosDAO().definirItemCombo(cmbTipoObjeto, objetoSelecionado.getId());

        tfdDescricao.requestFocus();
    }

    private void popularTabela() {
        alterarBotoesEdicao(false);

        Object[] cabecalho = {"Tipo", "Titulo/Descrição", "Editora", "Autor", "Status"};

        DefaultTableModel model = new DefaultTableModel(cabecalho, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        System.out.println("DML: " + criarFiltro());

        objetos = new ObjetoDAO().consultar(criarFiltro());

        for (Objeto objeto : objetos) {
            TipoObjeto tipo = new TipoObjetoDAO().consultarId(objeto.getTipo());
            Status status = new StatusDAO().consultarId(objeto.getStatus());

            Object[] row = {
                tipo.getDescricao(),
                objeto.getTitulo(),
                objeto.getPublisher(),
                objeto.getAutor(),
                status.getDescricao()
            };

            model.addRow(row);
        }

        tblListagem.setModel(model);

        tblListagem.setSelectionMode(0);
    }

    private String criarFiltro() {
        String dml = "SELECT * FROM objeto WHERE  id > 0 ";

        if (cmbFiltroTipo.getSelectedIndex() > 0) {
            String add = "AND tipo_objeto_id = " + ((ComboItem) cmbFiltroTipo.getSelectedItem()).getId() + " ";
            dml = dml + add;
        }

        if (cmbFiltroStatus.getSelectedIndex() > 0) {
            String add = "AND status_id = " + ((ComboItem) cmbFiltroStatus.getSelectedItem()).getId() + " ";
            dml = dml + add;
        }

        if (tfdFiltroDescricao.getText().trim().length() > 0) {
            String add = "AND titulo ILIKE '%" + tfdFiltroDescricao.getText() + "%' ";
            dml = dml + add;
        }

        if (tfdFiltroAutor.getText().trim().length() > 0) {
            String add = "AND autor ILIKE '%" + tfdFiltroAutor.getText() + "%' ";
            dml = dml + add;
        }

        if (tfdFiltroEditora.getText().trim().length() > 0) {
            String add = "AND publisher ILIKE '%" + tfdFiltroEditora.getText() + "%' ";
            dml = dml + add;
        }

        return dml + "ORDER BY titulo;";
    }

    private boolean verificarCampos() {
        Automatizar.nome(tfdDescricao, false);
        Automatizar.nome(tfdEditora, false);
        Automatizar.nome(tfdAutor, true);
        Automatizar.comboBox(cmbTipoObjeto, false);

        return (Automatizar.nome(tfdDescricao, false)
                || Automatizar.nome(tfdEditora, false)
                || Automatizar.nome(tfdAutor, true)
                || Automatizar.comboBox(cmbTipoObjeto, false));

    }

    private void alterarBotoesEdicao(boolean setTo) {
        btnEditar.setEnabled(setTo);
        btnExcluir.setEnabled(setTo);
        btnPerdido.setEnabled(setTo);
    }

    private void limparFiltros() {
        tfdFiltroDescricao.setText("");
        tfdFiltroAutor.setText("");
        tfdFiltroEditora.setText("");
        cmbFiltroTipo.setSelectedIndex(0);
        cmbFiltroStatus.setSelectedIndex(0);
    }

    private void salvar() {
        Objeto objeto = criarEntidade();

        if (objetoSelecionado == null) {
            if (new ObjetoDAO().salvar(objeto) == null) {
                JOptionPane.showMessageDialog(this, Formatacao.mensagemSalvarSucess("Objeto"));
                limparFormularioCadastro();
                popularTabela();
            } else {
                JOptionPane.showMessageDialog(this, Formatacao.mensagemSalvarError("Objeto"));
            }
        } else {
            if (new ObjetoDAO().atualizar(objeto) == null) {
                JOptionPane.showMessageDialog(this, Formatacao.mensagemAtualizarSucess("Objeto"));
                objetoSelecionado = null;
                limparFormularioCadastro();
                popularTabela();
            } else {
                JOptionPane.showMessageDialog(this, Formatacao.mensagemAtualizarError("Objeto"));
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlCadastrar;
    private javax.swing.JPanel PnlListagem;
    private javax.swing.JTabbedPane TbpObjeto;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEditarTipoObjeto;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnExcluirTipoObjeto;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnLimparFiltros;
    private javax.swing.JButton btnNovoTipoObjeto;
    private javax.swing.JButton btnPerdido;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbFiltroStatus;
    private javax.swing.JComboBox<String> cmbFiltroTipo;
    private javax.swing.JComboBox<String> cmbTipoObjeto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblListagem;
    private javax.swing.JTextField tfdAutor;
    private javax.swing.JTextField tfdDescricao;
    private javax.swing.JTextField tfdEditora;
    private javax.swing.JTextField tfdFiltroAutor;
    private javax.swing.JTextField tfdFiltroDescricao;
    private javax.swing.JTextField tfdFiltroEditora;
    // End of variables declaration//GEN-END:variables
}
